[paths]
usd_mesh      = "/fast_data/zhangziyang/workspace/RL2Path/outputs/scene_3/obstacles.obj"

lidar_dataset = "/mnt/nas_7/datasets/NavScene/lidar_dataset_simple_0.5_1.2_2d.h5"  
path_dataset  = "/mnt/nas_9/group/zhouboyang/merged_data_2d_simple_env_0.5_dis_0.5.npz"     
output        = "/mnt/nas_7/datasets/NavScene/demonstrations_simple_0.5_1.2_2d_ng.h5" 

[lidar]
count              = 1
name               = "Lidar"
translation        = [6.0, 0.0, 1.0]
rotation_frequency = 0.0            # 0 = 一帧扫描 360°
fov                = [360.0, 0.0]   # (水平°, 垂直°)
resolution         = [0.5625, 0.4]    # (水平°, 垂直°)
valid_range        = [0.05, 12.0]

[collect]
lidar_height  = 1.0
save_interval = 10_000               # 每 N 帧 flush HDF5

[process]
mode       = "2d"   # "2d" 或 "3d"
action_dim = 8
num_envs   = 1
sample_n   = -1     # <=0 表示全部样本
max_distance = 1.0

[imitation]
model = "tcnn_v0"

checkpoint_dir = "./outputs/ckpts/tcnn_v0"
log_dir = "./logs/imitation_bc/tcnn_v0"

seed = 3407
device = "cuda:1"
resume = true
resume_model_path = "./outputs/ckpts/tcnn_v0/model_7"

feature_dim = 256

batch_size = 512