<?xml version="1.0"?>
<package format="3">
  <name>vision_demo_host</name>
  <version>0.1.0</version>
  <description>Host-side visual acceptance demo skeleton for Orin.</description>
  <maintainer email="user@example.com">vision_demo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <build_depend>pkg-config</build_depend>
  <build_depend>libavcodec-dev</build_depend>
  <build_depend>libavformat-dev</build_depend>
  <build_depend>libavutil-dev</build_depend>
  <exec_depend>libavcodec-dev</exec_depend>
  <exec_depend>libavformat-dev</exec_depend>
  <exec_depend>libavutil-dev</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
